apiVersion: apps/v1
kind: Deployment
metadata:

  name: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: portfolio-app
        image: {{ .Values.werf.image.portfolio }}
        command: ["/app/start.sh"]
        ports:
        - containerPort: 8000
