apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
    # kubernetes.io/ingress.class: nginx
  name: werf-guide-app
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: werf-guide-app
            port:
              number: 8000
