---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-ru"

spec:
  selector:
    app: "{{ .Chart.Name }}-ru"
  ports:
  - name: http
    port: {{ .Values.port }}
    protocol: TCP
  - name: metrics
    port: 9100
    protocol: TCP
